import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.css';

import CartsProvider from '@/providers/cartsProvider';
import Menu from "./components/client/Menu";
import AuthProvider from '@/providers/authProvider';
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
title: "Create Next App",
description: "Generated by create next app",
};
export default function RootLayout({ children }) {
return (
<html lang="en">
<body className={inter.className}>

<CartsProvider>
<AuthProvider>
<Menu/>
{children}
</AuthProvider>
</CartsProvider>
</body>
</html>
);
}